// User types
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_OUT_USER = "LOG_OUT";
export const LOG_IN_FAIL = "LOG_IN_FAIL";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const VERIFY_USER_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_USER_FAIL = "VERIFY_FAIL";
export const CREATE_SOCKET = "CREATE_SOCKET"