export const lightTheme = {
  body: '#9f9f9fa8',
  text: 'black',
  header: '#a2a1a2',
  toggleBorder: '#FFF',
  background: '#3b3b3b',
  border: '1px solid white',
  inverseBackground: '#3b3838',
  inverseText: 'white',
  icon: '#444242',
  elementBackground: '#d2d2d2',
  buttonBackground: 'white',
  cardBackground: '#84827c',
  modalBackground: '#9ca4a2',
  commentBackground: 'lightgrey',
}
export const darkTheme = {
  body: '#363537',
  header: '',
  text: '#cbcbcb',
  toggleBorder: '#6B8096',
  background: '#999',
  border: '1px solid grey',
  inverseBackground: 'white',
  inverseText: 'black',
  icon: 'white',
  elementBackground: '#282828',
  buttonBackground: 'darkgrey',
  cardBackground: '#1a1a1b',
  modalBackground: '#272729',
  commentBackground: '#333333'
}